//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MustafaCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using CompareAttribute = System.ComponentModel.DataAnnotations.CompareAttribute;


    //System.ComponentModel.DataAnnotations.EmailAddressAttribute gives error

    public partial class User
    {
        public int UserID { get; set; }

        //[Remote("TrimString", "User")]
        
        
        [Required(ErrorMessage = "* This field  is required")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "* Must be 4 - 20 characters long.")]
        public string Username { get; set; }


        [DataType(DataType.Password)]
        [Required(ErrorMessage = "* This field is required")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "* Must be 6 - 20 characters long.")]
        public string Password { get; set; }


        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "* Passwords do NOT match")]
        [Required(ErrorMessage = "* This field is required")]
        public string ConfirmPassword { get; set; }

        [DisplayName("Is Admin")]
        public Nullable<bool> IsAdmin { get; set; }


        [EmailAddress(ErrorMessage = "* Enter a valid email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "* This field is required")]
        [StringLength(35, MinimumLength = 4, ErrorMessage = "* Must be 4 - 35 characters long.")]
        public string Email { get; set; }


        [DisplayName("First Name")]
        [Required(ErrorMessage = "* This field is required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "* Only characters are allowed")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "* Must be 4 - 20 characters long.")]
        //[Remote("TrimString", "User")]
        public string firstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "* This field is required")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "* Only characters are allowed")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "* Must be 4 - 20 characters long.")]
        public string lastName { get; set; }

        public string ImagePath { get; set; }
        public string LoginErrorMessage { get; set; }

    }
}
